# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  batch: false  
  branches:
      include:
      - main 
    

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
    npm run build
  displayName: 'npm install and build'

- task: Docker@2
  inputs:
    repository: debjym/retailproject_frontend
    command: 'buildAndPush'
    Dockerfile: './Dockerfile'
    tags: '$(Build.BuildId)'
    containerRegistry: Docker-hub